# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        timezone: [America/Los_Angeles, Europe/Berlin, Asia/Singapore]

    steps:
      - uses: actions/checkout@v3
      - name: Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # Install dependencies
      - run: npm install

      # Run tests
      - name: Run Test
        run: jest >> $GITHUB_STEP_SUMMARY
        env:
          TZ: ${{ matrix.node-version }}
          NODE_OPTIONS: --experimental-vm-modules

      # Run tests
      # - name: Run Test
      #   uses: ArtiomTr/jest-coverage-report-action@v2
      #   env:
      #     TZ: ${{ matrix.node-version }}
      #     NODE_OPTIONS: --experimental-vm-modules
